pipeline {
    agent any
    stages {
        stage('init') {
            steps {
                echo 'start the process'
            }
        }
        stage('Gather data') {
            steps {
                script {
                    sh 'bash ./loadRepository.sh'
                }
            }
        }
        stage('Generate frontmatter') {
            steps {
                sh 'bash ./frontMatter.sh'
            }
        }
         stage('push data to module site') {
             environment{
		       GIT_CREDS = credentials('GIT_TOKEN')
		    }
            steps {

          

            sh 'bash ./loadModules.sh'
            sh '''#!/bin/bash

            
	        cd ./module-site/ModuleSite
	        git config --global user.email "exapmle@gmail.com"
            git config --global user.name "userName" 
            git checkout -b module_gen
            git add .           
             
            if [ -n "$(git status --porcelain)" ]; then
            git commit -m "add: all modules "
            git push https://${GIT_CREDS}@github.com/MovingBlocks/ModuleSite.git  module_gen -f
            curl -i -H "Authorization: token $GIT_CREDS" -X POST "https://api.github.com/repos/MovingBlocks/ModuleSite/pulls" 
            -d '{ "title": "Module generated by automation",
                  "base": "master",
                  "head": "module_gen",
                  "body": "Module generated using Jenkins pipeline"}'
            else
               echo "no changes";
            fi   
            '''
            
            }
        }
        stage('clean Workspace') {
            steps {
                cleanWs()
            }
        }
    }
}
